# https://peps.python.org/pep-0518/

[tool.black]
line-length = 120
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.env
  | \.vscode
)/
'''

[tool.mypy]
# https://mypy.readthedocs.io/en/stable/config_file.html
python_version = '3.11'
ignore_missing_imports = true
exclude = [
    'resource',
]
disallow_incomplete_defs = true
check_untyped_defs = true

[tool.isort]
profile = "hug"
skip = [".env", ".vscode", "mypy_cache", "resource"]