"""empty message

Revision ID: 7bea60a0685c
Revises: 
Create Date: 2024-04-14 16:10:52.585063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bea60a0685c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_field_map",
        sa.Column("field_name", sa.String(), nullable=False),
        sa.Column("field_type", sa.Integer(), nullable=False),
        sa.Column("enum_options", sa.JSON(), nullable=True),
        sa.Column("field_num", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("field_name"),
    )
    op.create_table(
        "patient_case",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("admission_number", sa.String(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("create_by", sa.String(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("update_by", sa.String(), nullable=False),
        sa.Column("field_int_1", sa.Integer(), nullable=True),
        sa.Column("field_int_2", sa.Integer(), nullable=True),
        sa.Column("field_int_3", sa.Integer(), nullable=True),
        sa.Column("field_int_4", sa.Integer(), nullable=True),
        sa.Column("field_int_5", sa.Integer(), nullable=True),
        sa.Column("field_int_6", sa.Integer(), nullable=True),
        sa.Column("field_int_7", sa.Integer(), nullable=True),
        sa.Column("field_int_8", sa.Integer(), nullable=True),
        sa.Column("field_int_9", sa.Integer(), nullable=True),
        sa.Column("field_int_10", sa.Integer(), nullable=True),
        sa.Column("field_int_11", sa.Integer(), nullable=True),
        sa.Column("field_int_12", sa.Integer(), nullable=True),
        sa.Column("field_int_13", sa.Integer(), nullable=True),
        sa.Column("field_int_14", sa.Integer(), nullable=True),
        sa.Column("field_int_15", sa.Integer(), nullable=True),
        sa.Column("field_int_16", sa.Integer(), nullable=True),
        sa.Column("field_int_17", sa.Integer(), nullable=True),
        sa.Column("field_int_18", sa.Integer(), nullable=True),
        sa.Column("field_int_19", sa.Integer(), nullable=True),
        sa.Column("field_int_20", sa.Integer(), nullable=True),
        sa.Column("field_int_21", sa.Integer(), nullable=True),
        sa.Column("field_int_22", sa.Integer(), nullable=True),
        sa.Column("field_int_23", sa.Integer(), nullable=True),
        sa.Column("field_int_24", sa.Integer(), nullable=True),
        sa.Column("field_int_25", sa.Integer(), nullable=True),
        sa.Column("field_int_26", sa.Integer(), nullable=True),
        sa.Column("field_int_27", sa.Integer(), nullable=True),
        sa.Column("field_int_28", sa.Integer(), nullable=True),
        sa.Column("field_int_29", sa.Integer(), nullable=True),
        sa.Column("field_int_30", sa.Integer(), nullable=True),
        sa.Column("field_float_1", sa.Float(), nullable=True),
        sa.Column("field_float_2", sa.Float(), nullable=True),
        sa.Column("field_float_3", sa.Float(), nullable=True),
        sa.Column("field_float_4", sa.Float(), nullable=True),
        sa.Column("field_float_5", sa.Float(), nullable=True),
        sa.Column("field_float_6", sa.Float(), nullable=True),
        sa.Column("field_float_7", sa.Float(), nullable=True),
        sa.Column("field_float_8", sa.Float(), nullable=True),
        sa.Column("field_float_9", sa.Float(), nullable=True),
        sa.Column("field_float_10", sa.Float(), nullable=True),
        sa.Column("field_float_11", sa.Float(), nullable=True),
        sa.Column("field_float_12", sa.Float(), nullable=True),
        sa.Column("field_float_13", sa.Float(), nullable=True),
        sa.Column("field_float_14", sa.Float(), nullable=True),
        sa.Column("field_float_15", sa.Float(), nullable=True),
        sa.Column("field_float_16", sa.Float(), nullable=True),
        sa.Column("field_float_17", sa.Float(), nullable=True),
        sa.Column("field_float_18", sa.Float(), nullable=True),
        sa.Column("field_float_19", sa.Float(), nullable=True),
        sa.Column("field_float_20", sa.Float(), nullable=True),
        sa.Column("field_float_21", sa.Float(), nullable=True),
        sa.Column("field_float_22", sa.Float(), nullable=True),
        sa.Column("field_float_23", sa.Float(), nullable=True),
        sa.Column("field_float_24", sa.Float(), nullable=True),
        sa.Column("field_float_25", sa.Float(), nullable=True),
        sa.Column("field_float_26", sa.Float(), nullable=True),
        sa.Column("field_float_27", sa.Float(), nullable=True),
        sa.Column("field_float_28", sa.Float(), nullable=True),
        sa.Column("field_float_29", sa.Float(), nullable=True),
        sa.Column("field_float_30", sa.Float(), nullable=True),
        sa.Column("field_str_1", sa.String(), nullable=True),
        sa.Column("field_str_2", sa.String(), nullable=True),
        sa.Column("field_str_3", sa.String(), nullable=True),
        sa.Column("field_str_4", sa.String(), nullable=True),
        sa.Column("field_str_5", sa.String(), nullable=True),
        sa.Column("field_str_6", sa.String(), nullable=True),
        sa.Column("field_str_7", sa.String(), nullable=True),
        sa.Column("field_str_8", sa.String(), nullable=True),
        sa.Column("field_str_9", sa.String(), nullable=True),
        sa.Column("field_str_10", sa.String(), nullable=True),
        sa.Column("field_str_11", sa.String(), nullable=True),
        sa.Column("field_str_12", sa.String(), nullable=True),
        sa.Column("field_str_13", sa.String(), nullable=True),
        sa.Column("field_str_14", sa.String(), nullable=True),
        sa.Column("field_str_15", sa.String(), nullable=True),
        sa.Column("field_str_16", sa.String(), nullable=True),
        sa.Column("field_str_17", sa.String(), nullable=True),
        sa.Column("field_str_18", sa.String(), nullable=True),
        sa.Column("field_str_19", sa.String(), nullable=True),
        sa.Column("field_str_20", sa.String(), nullable=True),
        sa.Column("field_str_21", sa.String(), nullable=True),
        sa.Column("field_str_22", sa.String(), nullable=True),
        sa.Column("field_str_23", sa.String(), nullable=True),
        sa.Column("field_str_24", sa.String(), nullable=True),
        sa.Column("field_str_25", sa.String(), nullable=True),
        sa.Column("field_str_26", sa.String(), nullable=True),
        sa.Column("field_str_27", sa.String(), nullable=True),
        sa.Column("field_str_28", sa.String(), nullable=True),
        sa.Column("field_str_29", sa.String(), nullable=True),
        sa.Column("field_str_30", sa.String(), nullable=True),
        sa.Column("field_datetime_1", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_2", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_3", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_4", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_5", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_6", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_7", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_8", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_9", sa.DateTime(), nullable=True),
        sa.Column("field_datetime_10", sa.DateTime(), nullable=True),
        sa.Column("field_enum_1", sa.String(), nullable=True),
        sa.Column("field_enum_2", sa.String(), nullable=True),
        sa.Column("field_enum_3", sa.String(), nullable=True),
        sa.Column("field_enum_4", sa.String(), nullable=True),
        sa.Column("field_enum_5", sa.String(), nullable=True),
        sa.Column("field_enum_6", sa.String(), nullable=True),
        sa.Column("field_enum_7", sa.String(), nullable=True),
        sa.Column("field_enum_8", sa.String(), nullable=True),
        sa.Column("field_enum_9", sa.String(), nullable=True),
        sa.Column("field_enum_10", sa.String(), nullable=True),
        sa.Column("field_enum_11", sa.String(), nullable=True),
        sa.Column("field_enum_12", sa.String(), nullable=True),
        sa.Column("field_enum_13", sa.String(), nullable=True),
        sa.Column("field_enum_14", sa.String(), nullable=True),
        sa.Column("field_enum_15", sa.String(), nullable=True),
        sa.Column("field_enum_16", sa.String(), nullable=True),
        sa.Column("field_enum_17", sa.String(), nullable=True),
        sa.Column("field_enum_18", sa.String(), nullable=True),
        sa.Column("field_enum_19", sa.String(), nullable=True),
        sa.Column("field_enum_20", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("patient_case")
    op.drop_table("case_field_map")
    # ### end Alembic commands ###
